"""
Django settings for seedstore project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from decouple import config
from decouple import Csv, Config, RepositoryEnv

# This is optional, but you can make sure the path is correct:


from pathlib import Path
#from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOGIN_URL = '/admin/login/'  # Redirects to admin login if user is not logged in
import os
from decouple import config

PHONEPE_CLIENT_ID = config("PHONEPE_CLIENT_ID")
PHONEPE_CLIENT_SECRET = config("PHONEPE_CLIENT_SECRET")
PHONEPE_CLIENT_VERSION = config("PHONEPE_CLIENT_VERSION", default="1")
PHONEPE_ENV = config("PHONEPE_ENV", default="PRODUCTION")

PHONEPE_WEBHOOK_USER = config("PHONEPE_WEBHOOK_USER", default="olivia19")
PHONEPE_WEBHOOK_PASSWORD = config("PHONEPE_WEBHOOK_PASSWORD", default="olivia123")


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

config = Config(RepositoryEnv(BASE_DIR / '.env'))  # for custom path

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+vofv8mk!los^y4r=^^bt86$nk3e(^a$*i4k-_q7ybwpzwg5%c'

ALLOWED_HOSTS = ["hasafarm.com","www.hasafarm.com","hasaorganicseeds.com","www.hasaorganicseeds.com","147.93.28.237","127.0.0.1","localhost"]
# ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',
    'users',
    'cart',
    'orders',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.AutoLogout',  # Add this line
]

ROOT_URLCONF = 'seedstore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'seedstore' / 'templates',  # This points to 'templates' directory inside 'seedstore'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'seedstore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'hasaorganicseeds',  # Your database name
        'USER': 'postgres',  # Default PostgreSQL user
        'PASSWORD': 'NewStrongPassword',  # Replace with your actual password
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "/home/seedstore/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",  # The static directory at project level
]




# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session expires after 1 hour (3600 seconds)
SESSION_COOKIE_AGE =86400

# Allow session persistence for the given duration
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Use secure session storage
SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Store sessions in DB
SESSION_COOKIE_AGE = 1209600  # 2 weeks (in seconds)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Keep sessions even after closing browser
SESSION_SAVE_EVERY_REQUEST = True  # Extend session on activity



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.hostinger.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True           # ✅ use TLS
EMAIL_USE_SSL = False          # ✅ disable SSL
EMAIL_HOST_USER = 'contact@hasafarm.com'
EMAIL_HOST_PASSWORD = '8Hasa@seeds'
DEFAULT_FROM_EMAIL = 'Hasa Farm <contact@hasafarm.com>'
ADMIN_NOTIFICATION_EMAIL = 'contact@hasafarm.com'  # Receive order notifications here


CSRF_TRUSTED_ORIGINS = [
    "https://hasafarm.com",
    "http://hasafarm.com",
    "https://www.hasafarm.com",
    "http://www.hasafarm.com",
    "https://147.93.28.237",
    "http://147.93.28.237",
]