# Generated by Django 5.1.7 on 2026-09-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('campaign', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('email', 'campaign')},
            },
        ),
    ]
