# Generated by Django 5.1.7 on 2025-05-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cf_order_id_order_order_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
