# Generated by Django 5.1.7 on 2025-05-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_order_token_order_cashfree_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cashfree_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
