# Generated by Django 5.1.7 on 2025-06-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_cashfree_order_id_order_order_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
