# Generated by Django 5.1.7 on 2025-06-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phonepe_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
