# Generated by Django 5.1.7 on 2025-05-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='category',
        ),
        migrations.AddField(
            model_name='seed',
            name='categories',
            field=models.ManyToManyField(related_name='seeds', to='products.category'),
        ),
    ]
