# Generated by Django 5.1.7 on 2025-05-05 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_seed_category_seed_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='categories',
        ),
        migrations.AddField(
            model_name='seed',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
